### ISSUE TITLE
[Suggestion] Mod Management & Settings

### ISSUE THREAD

**Issue by Notawallplan** [gemforce-team/BezelModLoader#15]
Present an interface in the game settings to allow adjusting mod variables or outright being able to disable/enable mods at will (with a restart of course).

**Comment by piepie62** [comment]
Hooo boy. Alright, this one definitely *is* in scope, I just don't really think we currently have the infrastructure set up to deal with it. I'm certainly interested in having something like this, but we'd need to first standardize mod settings (either through a code interface or through a shared config format), then build on the UI stuff that interacts with that. More thought would need to be put into when/how settings are loaded, as well; coremods currently would nearly certainly need their settings done with a restart, while normal mods may or may not be able to have their settings changed at runtime.

**Comment by piepie62** [comment]
Settings are now done. Disabling and enabling mods is an interesting thought, but I can't think of a good way to do it right now.

**Comment by piepie62** [comment]
Mod disabling is now done, making this feature complete
