### ISSUE TITLE
Hotkey references in info panels aren't updated/removed by Bezel

### ISSUE THREAD

**Issue by Shylie** [gemforce-team/BezelModLoader#22]
So far I've discovered the following locations:

- Build Icons
- Build Info Panels
- Create Gem Icons
- Create Gem Info Panels
- Throw Gem Bomb Icon
- Throw Gem Bomb Info Panel
- Strike Spell Icons
- Strike Spell Info Panels
- Time Controls
- Wave Stone Info Panels
- Mana Pool
- Gem Creation Grade Adjuster

See [here](https://imgur.com/a/KmgFFzp) for some relevant images.

**Comment by piepie62** [comment]
Fixed with the latest commit
